CREATE INDEX Pm_Pe_ix
       ON PARAMETRES_MEMBRES (id_personne);
CREATE INDEX Ut_ix
       ON UTILISATEUR (id_utilisateur);
CREATE INDEX Pm_Pe_ix
       ON PARAMETRES_MEMBRES (id_utilisateur);
CREATE INDEX So_Ut_ix
       ON SOUSCRIPTION (id_utilisateur);
CREATE INDEX So_Pr_ix
       ON SOUSCRIPTION (id_programme_regime);
CREATE INDEX Ra_Pr_ix
       ON REGIME_ACTIVITE (id_programme_regime);
CREATE INDEX Ra_Ac_ix
       ON REGIME_ACTIVITE (id_activite);
CREATE INDEX Pr_Rr_ix
       ON REGIME_REPAS (id_programme_regime);
CREATE INDEX Pr_Rr_ix
       ON REGIME_REPAS (id_repas);
CREATE INDEX Re_IR_ix
       ON INGREDIENTS_REPAS (id_repas);
CREATE INDEX Re_IR_ix
       ON INGREDIENTS_REPAS (id_ingredient
       );