ALTER TABLE PARAMETRES_MEMBRES
MODIFY id_personne INT NOT NULL
MODIFY id_utilisateur INT NOT NULL
MODIFY masse_initiale FLOAT(10) NOT NULL
MODIFY taille_utilisateur FLOAT(10) NOT NULL
MODIFY date_debut_souscription DATE NOT NULL;