ALTER TABLE PERSONNE
MODIFY id_personne INT NOT NULL
MODIFY nom_personne VARCHAR(50) NOT NULL
MODIFY prenom_personne VARCHAR(50) NOT NULL
MODIFY date_naissance DATE NOT NULL
MODIFY genre CHAR(10) NOT NULL
;